# Gradle Properties
org.gradle.jvmargs=-Xmx2G

# Mod Properties
mod_version = 1.0.0
maven_group = com.maxim.meincoolermod
archives_base_name = mein-cooler-mod

# Fabric Properties
minecraft_version = 1.21
yarn_mappings = 1.21+build.9
loader_version = 0.15.11
fabric_version = 0.100.0+1.21 # <-- HINZUGEFÜGT

# Mod ID - Muss mit fabric.mod.json übereinstimmen!
mod_id = meincoolermod